### ISSUE TITLE
DONT_BRIDGE, DONT_BRIDGE_UNLESS_IN_ATTRS and LOCAL_METHODS appear in tab completion

### ISSUE THREAD

**Issue by fmagin** [justfoxing/ghidra_bridge#21]
`DONT_BRIDGE`, `DONT_BRIDGE_UNLESS_IN_ATTRS` and `LOCAL_METHODS` appear as suggestions in tab completion with IPython for some objects, but only when not using Jedi

```python
import ghidra_bridge
import IPython.utils.dir2
b = ghidra_bridge.GhidraBridge(namespace=globals())
fm = currentProgram.getFunctionManager()
IPython.utils.dir2.dir2(fm)
```

The weird thing is that neither `dir(fm)` nor `fm.__dir__()` actually contain those attributes, only dir2() returns them. Will look into this.

**Comment by fmagin** [comment]
Ok, the problem is that `dir(fm.__class__)` returns them which is added to the list `dir2` returns. So maybe make them "private" (i.e. prefix them with an underscore) or find some to remove them from the result of `dir(class)` somehow

**Comment by justfoxing** [comment]
PR merged.
