### ISSUE TITLE
How to commit params automatically? 

### ISSUE THREAD

**Issue by TylerKann** [justfoxing/ghidra_bridge#46]
I am trying to use ghidra to find the params of a function. That part is pretty easy to use using ghidra_bridge. However, it only works when the params have been commited (you can do this by just going to the function decompiler and pressing P or right clicking -> commit params). My end goal would be to do have this all done automatically, by one python script. Is there anyway to commit params automatically, or just another way of going about recovering this? Thanks! love the app!

**Comment by justfoxing** [comment]
So, this sounds like it's more a question about how to achieve something in the Ghidra scripting API, not so much about ghidra_bridge (ghidra_bridge is just focused on exposing that API remotely, not about using the API itself).

I'd suggest:

1. check the API documentation that ships with Ghidra (see the docs/ directory for GhidraAPI_javadoc.zip - I don't know how to achieve what you want, but a quick search shows the HighFunction class has a method called commitParamsToDatabase which sounds like you might want to check it out)

1. check the source code for Ghidra to see what implements that button in the decompiler, to see if it's exposed in the API

1. open an issue with the Ghidra team to see if they can help you better.
