### ISSUE TITLE
How to import ghidra in ghidra_bridge?

### ISSUE THREAD

**Issue by TylerKann** [justfoxing/ghidra_bridge#47]
Whenever i try import ghidra it says module not found. Can you only import ghidra if you are actually within the ghidra app? If so, is there other ways of achieving all the functionality of ghidra headlessly? 
Thanks!

**Comment by justfoxing** [comment]
Yeah, directly calling `import ghidra` will only work in the ghidra environment - not in ghidra_bridge. Instead, you have two options for getting access to the ghidra components in a ghidra_bridge environment.

1. Create your ghidra_bridge with the namespace argument set to `globals()` - something like `b = ghidra_bridge.GhidraBridge(namespace=globals())`. This will automatically load the ghidra module (as well as the flat API) into your global namespace, so you can just use `ghidra.whatever.whatever` from that point onwards. See `Setup Client` in the README for a slightly more detailed example of this.

1. If you don't want to pollute your namespace that much, you can create the bridge as something like `b = ghidra_bridge.GhidraBridge()`, then get the ghidra module with `remote_ghidra = b.get_ghidra_api()`. Accessing components of that would then look something like `remote_ghidra.whatever.whatever...`. You can use `get_java_api()` and `get_flat_api()` in the same way.
