### ISSUE TITLE
analyze(currentProgram) may not be working 

### ISSUE THREAD

**Issue by TylerKann** [justfoxing/ghidra_bridge#49]
I posted here yesterday about a timeout I was getting with analyze(), and the following was suggested : 
`b.bridge.remote_eval("analyze(currentProgram)", timeout_override=<value>)` . However, I am not sure this works . I am experiencing one of two issues (although it is hard to tell): 
it either is not analyzing the program, or it is analyzing the program but never finishing after analysis.  
When I run this command I can never break out. I know analyze() takes a long time, but when I do it in ghidra, it runs faster than when I do it in ghidra_bridge (which is never). Since this is newly implemented, could this maybe be a bug? Thanks!

**Comment by justfoxing** [comment]
Hmm, nope, the -1 timeout override is working for just fine for me with analyze(). Not being able to break out is an aspect of the bridge waiting for a response.

Timing the code on my test program shows 121 seconds for running an analysis across the bridge vs 119 seconds running from the ghidra python interpreter, so it doesn't appear to be adding a significant delay.

Additionally, I'd suggest just not running the analysis through GhidraBridge if it's causing problems. Most ghidra scripts I've seen are based on the assumption that analysis has already been completed, either manually through the UI when the program is loaded, or by the analyzeHeadless script. If you're running this through analyzeHeadless, as long as you haven't used the -noanalysis flag, it'll already be analyzed for you.

**Comment by TylerKann** [comment]
okay maybe I will look into the analyze headless. Thanks @justfoxing . However I dont understand in the analyze headless, what `<project repository> <project> ` should be. What would this be?

**Comment by justfoxing** [comment]
The first two arguments to analyzeHeadless are a folder where the project file Ghidra creates is placed, and the name of the project file for Ghidra to create. These can be pretty much anything (e.g., /scratch/ghidra_projects TestProject), with the requirement that the folder must exist. For further info, please see the analyzeHeadlessREADME.html in your Ghidra distribution.
