### ISSUE TITLE
Handle iterators

### ISSUE THREAD

**Issue by justfoxing** [justfoxing/ghidra_bridge#5]
I got another behavior where the Jython shell returns different values than the Bridge.

I was implementing an Iterator for functions:
(for debugging purpose i added the additional variable)
```python
def func_iterator(funcs):
        got_next = funcs.hasNext()
        while got_next:
                yield funcs.next()
                got_next = funcs.hasNext()
                print(got_next)

b = ghidra_bridge.GhidraBridge(namespace=globals())
listing = currentProgram.getListing()
for func in func_iterator(listing.getFunctions(0)):
    print(func)
```

This does work perfectly in the Jython shell with the following output:
```
FUN_00081388
True
FUN_00081360
True
FUN_00081168
True
FUN_0008103c
False
```
As `FUN_0008103c` is the last function in the list..
However running it over the bridge:

```
FUN_00081360
True
FUN_00081168
True
FUN_0008103c
True
```

Then Java will of course throw an `NullPointerException: java.lang.NullPointerException` when checking for the next Object.

Further :-) it would be super improvement if your bride is returning a valid Iterator when the Object contains an Iterator.

_Originally posted by @Traxes in https://github.com/justfoxing/ghidra_bridge/issues/2#issuecomment-490445235_

**Comment by justfoxing** [comment]
Just pushed a fix for this.

The actual issue breaking your iterator was a straight up bug - I was incorrectly deserializing boolean values as they came in, so they were always being set to True. Pull a new copy and your code should work fine.

I've also added support for iterable/iterator objects - so as long as the bridge sees \_\_iter__/\_\_next__ /next in the object, it'll create them as BridgedIterable/Iterator objects that expose the right methods to Python. So the following should just work...
```
for func in currentProgram.getListing().getFunctions(0):
    print(func)
```

**Comment by Traxes** [comment]
Perfekt :-) Works !
