### ISSUE TITLE
Expose other IPC channels

### ISSUE THREAD

**Issue by JayFoxRox** [justfoxing/ghidra_bridge#59]
Consider Unix Domain Sockets for example: https://stackoverflow.com/a/29436429
*(Edit: This issue should probably have been on https://github.com/justfoxing/jfx_bridge)*

**Comment by justfoxing** [comment]
Was considered at design time (the extra throughput would be nice), but I wanted something that supported all the same platforms as Ghidra, and secondarily could work for remote endpoints.

I won't be pursuing this anytime soon (it's really just a nice-to-have, and I don't have enough spare cycles), but if you want to have a crack at adding it to jfx_bridge, go for your life.
