### ISSUE TITLE
Timeout Condition

### ISSUE THREAD

**Issue by 6r0k3d** [justfoxing/ghidra_bridge#67]
Not sure if this is ghidra or jfx or me using the libraries incorrectly-

I'm getting the FlatProgramAPI for a DLL the main program calls, then trying to get all the functions from that library-

```
	if func not in highfunction_cache:			
		if func.isExternal():
			origName = func.getExternalLocation().getOriginalImportedName()
			origName = origName.split("_")[1] # Ordinal_XXX, return XXX
			extMgr = currentProgram.getExternalManager()
			fpAPI = FlatProgramAPI(prog)
			funcMgr = prog.getFunctionManager()
			fns = funcMgr.getFunctions(True)
			for x in fns:
```

It looks like I can get the Function Manager for the external program, but when I try and get the functions, I get either a timeout or invalid arg:

![image](https://user-images.githubusercontent.com/42014669/154729810-a6fb4dae-a809-41e6-a83a-9c489117b9ec.png)

Any thoughts?

**Comment by justfoxing** [comment]
Not really enough info for me to go on. Can you please include the exception details for both the timeout and invalid arg errors you're reporting?

**Comment by 6r0k3d** [comment]
Thats whats weird, it never actually throws an exception, just gets stuck in an infinite loop. `prog` is the external library, which is opened here and passed to the snippet posted above:

```
	if func.isExternal():
		libPath = currentProgram.getExternalManager().getExternalLibrary(func.getExternalLocation().getLibraryName()).getAssociatedProgramPath()
		projectData = state.getProject().getProjectData()
		libFile = projectData.getFile(libPath)
		print(libFile)
		program = libFile.getImmutableDomainObject(libFile, DomainFile.DEFAULT_VERSION, monitor)
		print("func: ", func)
		print("program: ", program)
		
	hf = get_highfunction(func, program)
```

Then I try and get the function manager of the external program so I can iterate over its functions.

When I step through the for loop, `x` gets the following values (loops forever):
`_simpleInvalidArgException`
![image](https://user-images.githubusercontent.com/42014669/154753789-7e25ce47-be17-4b57-a6c2-13ddf3ae31b0.png)

`_simpleMemoryException`
![image](https://user-images.githubusercontent.com/42014669/154753892-836056d1-51df-4d8f-b541-88968137a266.png)

`_simpleNotSupportedException`
![image](https://user-images.githubusercontent.com/42014669/154754008-ec40b346-a13e-4419-b27f-dd28d46e88fa.png)

But when I try and see `fns` in the Watches window, it doesnt pull anything up:
![image](https://user-images.githubusercontent.com/42014669/154754102-0b762c34-b8f2-4815-9d06-a4db63b8dbb6.png)


It looks like it is getting different function managers:
![image](https://user-images.githubusercontent.com/42014669/154755321-cfe8ada3-a4eb-476d-9f16-f1d4146f9afa.png)

And I threw in this loop 
```
for x in currentProgram.getFunctionManager().getFunctions(True):
    print(x)
```

which properly printed out all the functions in the current program.

And this is printed to the ghidra console window (snippet, not the full output, but its just repeats of `shape` and `__len__`):
```
  File "C:\Users\student\Downloads\ghidra_10.0.4_PUBLIC_20210928\ghidra_10.0.4_PUBLIC\Ghidra\Features\Python\ghidra_scripts\jfx_bridge\bridge.py", line 992, in local_get
    result = getattr(target, name)
AttributeError: 'ghidra.program.database.function.FunctionManagerDB' object has no attribute 'shape'
Traceback (most recent call last):
  File "C:\Users\student\Downloads\ghidra_10.0.4_PUBLIC_20210928\ghidra_10.0.4_PUBLIC\Ghidra\Features\Python\ghidra_scripts\jfx_bridge\bridge.py", line 992, in local_get
    result = getattr(target, name)
AttributeError: 'ghidra.program.database.function.FunctionManagerDB' object has no attribute '__len__'
```

Can't seem to generate the Timeout again for some reason

**Comment by 6r0k3d** [comment]
@#$!
.............................

It's working fine. Those are literally just the first functions in the external library, and since theres 7k+ functions, its just real slow


![image](https://user-images.githubusercontent.com/42014669/154756572-abc9649c-b01c-4d18-91b5-3310ec461fc0.png)

**Comment by 6r0k3d** [comment]
Awesome! I'll check them out. You have a patreon or buy me a coffee or something?
