### ISSUE TITLE
isinstance comparison always BridgedObject

### ISSUE THREAD

**Issue by Traxes** [justfoxing/ghidra_bridge#7]
Hi Again :-), 

currently trying to run the following Code to get the length of a ClangVariableDecleration:
The Type is a `ghidra.app.decompiler.ClangSyntaxToken`

Example Code:
```python
listing = currentProgram.getListing()

decompInterface = ghidra.app.decompiler.DecompInterface()
decompInterface.openProgram(currentProgram)

for func in listing.getFunctions(0):
    decompileResults = decompInterface.decompileFunction(func, 30, monitor)
    if decompileResults.decompileCompleted():
        print("Function {}:".format(func))
        Clang_Function = decompileResults.getCCodeMarkup()
        for a in range(Clang_Function.numChildren()):
            #IPython.embed()
            if isinstance(Clang_Function.Child(a), ghidra.app.decompiler.ClangVariableDecl):
                print(Clang_Function.Child(a).dataType.getLength())
```

When comparing the result of `Clang_function.Child(a)` should be something close like `ghidra.app.decompiler.ClangVariableDecl`. However it is always a BridgedObject:
```
In [5]: Clang_Function.Child(a)
Out[5]: <BridgedObject(ClangSyntaxToken, handle=7466c8fd-7fa3-4afb-91dd-aa6a9439e6c5)>
```

Is there any way to get the type out of the BridgedObject?
Thanks :-)

**Comment by justfoxing** [comment]
To unblock your work quickly, you can grab the _bridge_type attribute,
which will be the string value of the type name (so
Clang_Function.Child(a)._bridge_type ==
"ghidra.app.decompiler.ClangVariableDecl" should work).

This is just a hacky workaround, though. It breaks the transparency
principle I'm shooting for (that you shouldn't need to know if an object is
bridged or not). I'll have a think about the best way to override
type/isinstance.

**Comment by justfoxing** [comment]
Just pushed v0.0.5 to tackle this.

Now, when you do a `GhidraBridge(namespace=globals())`, isinstance will get overwritten with ghidra_bridge.bridge.bridged_isinstance, which will check to see if the object and class(es) you're checking are either all local (in which case, it passes through to regular isinstance) or all bridged (in which case, it packs them off to the remote end of the bridge to run isinstance there).

There's a dangling question mark about what to do in the case where there's a bridged object and a local class, or a local object and a bridged class, but this seems not super likely for the ghidra_bridge use-case, so I've just defaulted to return False in that case.

So now, `isinstance(Clang_Function.Child(a), ghidra.app.decompiler.ClangVariableDecl)` should work just fine.
