### ISSUE TITLE
Wrong port in bridge from PyPi package

### ISSUE THREAD

**Issue by Masrepus** [justfoxing/ghidra_bridge#9]
When installing ghidra_bridge from PyPi, the default server port is listed as 34942, but actually the server starts on 34940. Please update the package

**Comment by justfoxing** [comment]
Oops. Thanks for the heads up. Not sure how I managed to desynchronize those.

I've fixed it on the other end - bridge.py has been set to 34942 in the repo. git pull down the latest version of that and the server will now start on the port that the 0.0.2 client package expects.

**Comment by Masrepus** [comment]
Alright, thanks for fixing it!
